### ISSUE TITLE
Merkle proof tracking issue

### ISSUE THREAD

**Issue by ralexstokes** [ralexstokes/ssz-rs#129]
Some relevant issues:

- [x] https://github.com/ralexstokes/ssz-rs/issues/122
- [ ] https://github.com/ralexstokes/ssz-rs/issues/123
- [x] https://github.com/ralexstokes/ssz-rs/issues/121
- [x] https://github.com/ralexstokes/ssz-rs/issues/103

Once the functionality is implemented, we should see which of the `consensus-spec-tests` we can implement here.
